# -*- coding: utf-8 -*-
"""Clase 1 Python 0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XbIO6sEOalY89klcQ6ZJN84Js0zKzoTZ

CURSO PYTHON COLSUBSIDIO Juan Leguizamo
"""

print("Hola mundo Soy juan")

"""**VARIABLES**"""

nombre = "juan leguizamo"
print(nombre)
telefono = 4552890
print(telefono)

nombre_per = input("digite su nombre")
print(nombre_per)